/**
 * Generates the local .env files for THIS machine.
 *
 * The SQLite DATABASE_URL must be an absolute path so the same DB file resolves
 * from both the Prisma CLI (cwd = packages/db) and the Next.js runtime (cwd =
 * apps/web). This script computes that path from the repo location, so moving
 * the project to a new machine just needs: `pnpm run setup:env`.
 *
 * It preserves an existing AUTH_SECRET if one is already present (so sessions
 * survive re-runs); otherwise it generates a strong random one.
 */
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dbFile = join(root, "packages", "db", "prisma", "dev.db").replace(/\\/g, "/");
const databaseUrl = `file:${dbFile}`;

const webEnvPath = join(root, "apps", "web", ".env.local");
const dbEnvPath = join(root, "packages", "db", ".env");

/** Read an existing var value from a .env file if present. */
function readVar(path, key) {
  if (!existsSync(path)) return undefined;
  const line = readFileSync(path, "utf8")
    .split(/\r?\n/)
    .find((l) => l.startsWith(`${key}=`));
  if (!line) return undefined;
  return line.slice(key.length + 1).replace(/^["']|["']$/g, "");
}

const authSecret =
  readVar(webEnvPath, "AUTH_SECRET") && readVar(webEnvPath, "AUTH_SECRET") !== "change-me"
    ? readVar(webEnvPath, "AUTH_SECRET")
    : randomBytes(32).toString("base64");

writeFileSync(
  dbEnvPath,
  `# Auto-generated by scripts/setup-env.mjs — Prisma CLI datasource.\nDATABASE_URL="${databaseUrl}"\n`,
);

writeFileSync(
  webEnvPath,
  `# Auto-generated by scripts/setup-env.mjs for this machine.
DATABASE_URL="${databaseUrl}"
AUTH_SECRET="${authSecret}"
APP_URL="http://localhost:3000"

# Email (off by default). Point at Mailpit for local testing.
EMAIL_ENABLED="false"
SMTP_HOST="localhost"
SMTP_PORT="1025"
SMTP_FROM="Workshop <no-reply@workshop.local>"
`,
);

console.log("Wrote env files for this machine:");
console.log(`  ${dbEnvPath}`);
console.log(`  ${webEnvPath}`);
console.log(`DATABASE_URL = ${databaseUrl}`);
console.log(existsSync(dbFile) ? "DB file found ✓" : "DB file NOT found — run `pnpm db:push && pnpm db:seed`");
