/**
 * Generates the local .env files for THIS machine.
 *
 * DATABASE_URL points at Postgres. The default is the local Docker Postgres from
 * docker-compose.yml (`docker compose up -d`). If you already set a different
 * DATABASE_URL (e.g. a hosted Postgres), a re-run PRESERVES it — it only fills in
 * the default when none is set yet (or the old SQLite `file:` URL is still there).
 *
 * It also preserves an existing AUTH_SECRET if present (so sessions survive
 * re-runs); otherwise it generates a strong random one.
 */
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Default local Postgres — matches docker-compose.yml. `docker compose up -d` first.
const DEFAULT_DATABASE_URL = "postgresql://workshop:workshop@localhost:5432/workshop?schema=public";

const webEnvPath = join(root, "apps", "web", ".env.local");
const dbEnvPath = join(root, "packages", "db", ".env");

/** Read an existing var value from a .env file if present. */
function readVar(path, key) {
  if (!existsSync(path)) return undefined;
  const line = readFileSync(path, "utf8")
    .split(/\r?\n/)
    .find((l) => l.startsWith(`${key}=`));
  if (!line) return undefined;
  return line.slice(key.length + 1).replace(/^["']|["']$/g, "");
}

// Preserve an existing custom Postgres URL; replace the old SQLite `file:` URL or fill the default.
const existingDbUrl = readVar(webEnvPath, "DATABASE_URL") ?? readVar(dbEnvPath, "DATABASE_URL");
const databaseUrl =
  existingDbUrl && !existingDbUrl.startsWith("file:") ? existingDbUrl : DEFAULT_DATABASE_URL;

const authSecret =
  readVar(webEnvPath, "AUTH_SECRET") && readVar(webEnvPath, "AUTH_SECRET") !== "change-me"
    ? readVar(webEnvPath, "AUTH_SECRET")
    : randomBytes(32).toString("base64");

writeFileSync(
  dbEnvPath,
  `# Auto-generated by scripts/setup-env.mjs — Prisma CLI datasource.\nDATABASE_URL="${databaseUrl}"\n`,
);

writeFileSync(
  webEnvPath,
  `# Auto-generated by scripts/setup-env.mjs for this machine.
DATABASE_URL="${databaseUrl}"
AUTH_SECRET="${authSecret}"
APP_URL="http://localhost:3000"

# Email (off by default). Point at Mailpit for local testing.
EMAIL_ENABLED="false"
SMTP_HOST="localhost"
SMTP_PORT="1025"
SMTP_FROM="Workshop <no-reply@workshop.local>"
`,
);

console.log("Wrote env files for this machine:");
console.log(`  ${dbEnvPath}`);
console.log(`  ${webEnvPath}`);
console.log(`DATABASE_URL = ${databaseUrl}`);
console.log("Next: `docker compose up -d` (start Postgres), then `pnpm db:migrate` (creates tables + seeds).");
